- name: advanced loops
  hosts: localhost
  become: yes
  tasks:
  - name: advanced loops
    ansible.builtin.yum:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'nginx', state: 'absent'}
     