- name: catalogue component
  hosts: catalogue
  become: yes
  tasks:
  - name: run the nodejs script
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"
  - name: install the nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed
  - name: check the robshop user exist or not
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true
  - name: print the out varible
    ansible.builtin.debug:
      msg: "the out variable is {{out}}" 
  - name: create the roboshop user
    ansible.builtin.user:
      name: roboshop
    when: out.rc != 0     
  - name: check the directory exist or not
    ansible.builtin.stat:
      path: /app
    register: directory
  - name: print the output variable
    ansible.builtin.debug:
      msg: "the variable of output is {{directory}}"
           