- name: catalogue component
  hosts: catalogue
  become: yes
  tasks:
  - name: run the nodejs script
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"
  - name: install the nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed
  - name: check the robshop user exist or not
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true
  - name: print the out varible
    ansible.builtin.debug:
      msg: "the out variable is {{out}}" 
  - name: create the roboshop user
    ansible.builtin.user:
      name: roboshop
    when: out.rc != 0     
  - name: check the directory exist or not
    ansible.builtin.stat:
      path: /app
    register: directory
  - name: print the output variable
    ansible.builtin.debug:
      msg: "the variable of output is {{directory}}"
  - when: directory.stat.exists == False
    name: create the app directory
    ansible.builtin.file:
      path: /app
      state: directory
      mode: '0755'   
  - name: Download the code
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp/catalogue.zip 
      mode: 0755
  - name: unzip the file
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  - name: install the dependinces
    ansible.builtin.command: npm install
    args:
     chdir: /app    

           