- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: checkthe user exist or not
    ansible.builtin.command: id super
    register: out
    ignore_errors: true
  - name: print the variable name
    ansible.builtin.debug:
      msg: "the output is {{out}}"
  - name: create the user
    ansible.builtin.user: 
      name: super
    when: out.rc != 0     
  - name: check the user present or not
    ansible.builtin.command: id super 
    register: out
  - name: print the variable name
    ansible.builtin.debug:
      msg: "check the user is presented or not {{out}}"
    