- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: checkthe user exist or not
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true
  - name: print the variable name
    ansible.builtin.debug:
      msg: "the output is {{out}}"
  - name: create the user
    ansible.builtin.user: 
      name: roboshop
    when: out.rc != 0     
    
    