- name: mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: copy the mongodbrepo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: install the mongodb
    ansible.builtin.yum:
      name: mongodb-org 
      state: installed
  - name: start and enabled the mongodb
    ansible.builtin.service:
       name: mongod
       state: started
       enabled: yes

