- name: can pass variables from file
  hosts: localhost
  vars_files:
  - variable.yaml
  - kishore.yaml
  task:
  - name: name of the tasks
    ansible.builtin.debug:
      msg: "the message is {{name}} and {{test}} and one is {{super}}"
  - name: the varibble value is coming from kishore.yaml
    ansible.builtin.debug:
      msg: "the message is {{name}},{{fruit}} and {{today}}"   

    